services:
  backend:
    build: ./backend
    container_name: barrier-backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    restart: always

  frontend:
    build: ./frontend
    container_name: barrier-frontend
    ports:
      - "3000:80"
    restart: always

  middleware:
    build: ./middleware
    container_name: barrier-middleware
    ports:
      - "6000:6000"
    environment:
      NODE_ENV: production
    restart: always